---
abstract: 'Middleware for session management'
author:
  - 'Tatsuhiko Miyagawa'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Session
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Digest::SHA1: 0
  Plack: 0.9910
resources:
  license: http://dev.perl.org/licenses/
version: 0.14
