---
abstract: 'Middleware for session management'
author:
  - 'Tatsuhiko Miyagawa'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Fatal: 0.006
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  CPAN::Meta: 0
  ExtUtils::MakeMaker: 6.36
dynamic_config: 0
generated_by: 'Module::Install version 1.06, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Session
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Digest::HMAC_SHA1: 1.03
  Digest::SHA1: 0
  Plack: 0.9910
resources:
  license: http://dev.perl.org/licenses/
version: 0.17
